from reportlab.lib import colors
import logging

logger = logging.getLogger(__name__)
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from app.schemas.presentation import PresentationStructure
import io

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        # Main Title Style
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.darkblue
        )
        # Slide Title Style
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=18,
            spaceBefore=20,
            spaceAfter=15,
            textColor=colors.black
        )
        # Bullet Point Style
        self.bullet_style = ParagraphStyle(
            'CustomBullet',
            parent=self.styles['BodyText'],
            fontSize=12,
            leading=16, # Line height
            spaceAfter=5
        )

    def generate(self, structure: PresentationStructure) -> io.BytesIO:
        """
        Converts the structured JSON into a PDF file in memory.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch
        )

        story = []

        # 1. Main Title
        story.append(Paragraph(structure.topic, self.title_style))
        story.append(Paragraph(f"Generated by SlideGenie AI", self.styles['Italic']))
        story.append(Spacer(1, 0.5 * inch))

        # 2. Iterate Slides/Sections
        for slide in structure.slides:
            # Section Title
            story.append(Paragraph(slide.title, self.heading_style))
            
            # Content Container (Table for Image + Text)
            # If image exists, we'll use a table to put them side-by-side
            
            # Bullet Points
            list_items = []
            for point in slide.points:
                item = ListItem(Paragraph(point, self.bullet_style), bulletColor=colors.black)
                list_items.append(item)
            
            bullets = ListFlowable(
                list_items,
                bulletType='bullet',
                start='circle',
                leftIndent=20
            )

            story.append(bullets)
            
            # Add Image if present (simplified: just below text in PDF)
            if slide.image_url:
                try:
                    from reportlab.platypus import Image as RLImage
                    story.append(Spacer(1, 0.2 * inch))
                    # Use a standard width to prevent overflow
                    img = RLImage(slide.image_url, width=4*inch, height=2.5*inch)
                    story.append(img)
                except Exception as e:
                    logger.error(f"Failed to add image to PDF: {e}")

            story.append(Spacer(1, 0.3 * inch))

        # 3. Final Closing
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph("Thank You for using SlideGenie AI!", self.styles['Heading2']))
        story.append(Paragraph("Innovating your presentation workflow with AI.", self.styles['Italic']))

        # 4. Build PDF
        doc.build(story)
        buffer.seek(0)
        
        return buffer

pdf_generator = PDFGenerator()
