from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from app.schemas.presentation import PresentationStructure
import io

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        # Main Title Style
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.darkblue
        )
        # Slide Title Style
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=18,
            spaceBefore=20,
            spaceAfter=15,
            textColor=colors.black
        )
        # Bullet Point Style
        self.bullet_style = ParagraphStyle(
            'CustomBullet',
            parent=self.styles['BodyText'],
            fontSize=12,
            leading=16, # Line height
            spaceAfter=5
        )

    def generate(self, structure: PresentationStructure) -> io.BytesIO:
        """
        Converts the structured JSON into a PDF file in memory.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch
        )

        story = []

        # 1. Main Title
        story.append(Paragraph(structure.topic, self.title_style))
        story.append(Paragraph(f"Generated by SlideGenie AI", self.styles['Italic']))
        story.append(Spacer(1, 0.5 * inch))

        # 2. Iterate Slides/Sections
        for slide in structure.slides:
            # Section Title
            story.append(Paragraph(slide.title, self.heading_style))
            
            # Bullet Points
            list_items = []
            for point in slide.points:
                item = ListItem(Paragraph(point, self.bullet_style), bulletColor=colors.black)
                list_items.append(item)
            
            # Add list to story
            story.append(
                ListFlowable(
                    list_items,
                    bulletType='bullet',
                    start='circle',
                    leftIndent=20
                )
            )
            
            # Spacer between sections (logic for page breaks could go here if strict 1-slide-per-page is needed)
            # For now, we allow flow but add spacing
            story.append(Spacer(1, 0.3 * inch))

        # 3. Build PDF
        doc.build(story)
        buffer.seek(0)
        
        return buffer

pdf_generator = PDFGenerator()
