from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from app.schemas.presentation import PresentationStructure
import io

class PPTGenerator:
    def __init__(self):
        self.LAYOUT_TITLE = 0
        self.LAYOUT_CONTENT = 1

    def generate(self, structure: PresentationStructure) -> io.BytesIO:
        """
        Converts the structured JSON into a .pptx file in memory.
        """
        prs = Presentation()

        # 1. Main Title Slide
        title_slide_layout = prs.slide_layouts[self.LAYOUT_TITLE]
        slide = prs.slides.add_slide(title_slide_layout)
        
        # Set Title
        title = slide.shapes.title
        title.text = structure.topic
        
        # Set Subtitle
        subtitle = slide.placeholders[1]
        subtitle.text = "Generated by SlideGenie AI"

        # 2. Content Slides
        for slide_data in structure.slides:
            slide_layout = prs.slide_layouts[self.LAYOUT_CONTENT]
            slide = prs.slides.add_slide(slide_layout)

            # Title
            title_shape = slide.shapes.title
            title_shape.text = slide_data.title

            # Content (Bullets)
            # Find the body placeholder (usually idx 1 in standard layout)
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True

            # Clear existing empty paragraphs if any or just start adding
            tf.clear() 

            for point in slide_data.points:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
                
                # Basic Formatting
                p.font.size = Pt(18)
                p.space_after = Pt(10)

        # 3. Save to memory
        output = io.BytesIO()
        prs.save(output)
        output.seek(0)
        
        return output

ppt_generator = PPTGenerator()
